name: Sync wiki

on:
  push:
    branches:
      - main
    paths:
      - 'wiki/**'
      - '.github/workflows/wiki-sync.yml'

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # REQUIRED on some repos

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v3
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_NAME: github-actions
          GH_MAIL: github-actions@github.com
          WIKI_DIR: wiki
          WIKI_BRANCH: main
